name: Publish Python 🐍 distribution to PyPI

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (or change to your default branch)

jobs:
  build:
    runs-on: ubuntu-latest  # This runs on an Ubuntu virtual environment

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2  # This checks out your repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # You can change the version to your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine  # Install necessary build tools for packaging

    - name: Build the distribution
      run: |
        python setup.py sdist bdist_wheel  # Build the source and wheel distribution files

    - name: Upload to PyPI
env:
  PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
 # This accesses the secret token you set in GitHub
      run: |
        twine upload dist/* -u __token__ -p $PYPI_API_TOKEN  # Upload the built package to PyPI
